In [19]:
import pandas as pd
import numpy as np
import matplotlib as plt

from scipy.stats import kruskal

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

from sklearn.model_selection import train_test_split

In [20]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [21]:
X_train = pd.read_csv('train.csv')
X_test = pd.read_csv('test.csv')

In [22]:
X_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [23]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [24]:
X_train.shape

(1460, 81)

In [25]:
y_train = X_train['SalePrice']
X_train = X_train.drop('SalePrice', axis=1)



X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [26]:
X_train.isna().sum()[X_train.isna().sum() > 0].reset_index()

           index     0
0    LotFrontage   217
1          Alley  1094
2     MasVnrType   683
3     MasVnrArea     6
4       BsmtQual    28
5       BsmtCond    28
6   BsmtExposure    28
7   BsmtFinType1    28
8   BsmtFinType2    28
9     Electrical     1
10   FireplaceQu   547
11    GarageType    64
12   GarageYrBlt    64
13  GarageFinish    64
14    GarageQual    64
15    GarageCond    64
16        PoolQC  1162
17         Fence   935
18   MiscFeature  1122

In [27]:
cols_with_na =X_train.loc[:, X_train.isna().sum() > 600]
X_train = X_train.drop(cols_with_na, axis=1)
X_test = X_test.drop(cols_with_na, axis=1)

In [28]:
pipe1 = Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                      ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [29]:
pipe2 = Pipeline(steps=[('numerical', SimpleImputer(strategy='mean')),
                      ('scaler', StandardScaler())])

In [30]:

preprocessor = ColumnTransformer(
    [
    ('numerical', pipe2, make_column_selector(dtype_include='number')),
    ('categorical', pipe1, make_column_selector(dtype_include='object'))
    
]
)


pipeline = Pipeline([
    ('preprocessor', preprocessor)
])



X_train_transformed = pipeline.fit_transform(X_train)
X_val_transformed =pipeline.transform(X_val)
X_test_transformed = pipeline.transform(X_test)


transformed_columns = preprocessor.get_feature_names_out()

X_train_transformed = pd.DataFrame(X_train_transformed.toarray(), columns=transformed_columns)
X_val_transformed = pd.DataFrame(X_val_transformed.toarray(), columns=transformed_columns)
X_test_transformed = pd.DataFrame(X_test_transformed.toarray(), columns=transformed_columns)

X_train_transformed.head()

,numerical__Id,numerical__MSSubClass,numerical__LotFrontage,numerical__LotArea,numerical__OverallQual,numerical__OverallCond,numerical__YearBuilt,numerical__YearRemodAdd,numerical__MasVnrArea,numerical__BsmtFinSF1,numerical__BsmtFinSF2,numerical__BsmtUnfSF,numerical__TotalBsmtSF,numerical__1stFlrSF,numerical__2ndFlrSF,numerical__LowQualFinSF,numerical__GrLivArea,numerical__BsmtFullBath,numerical__BsmtHalfBath,numerical__FullBath,numerical__HalfBath,numerical__BedroomAbvGr,numerical__KitchenAbvGr,numerical__TotRmsAbvGrd,numerical__Fireplaces,numerical__GarageYrBlt,numerical__GarageCars,numerical__GarageArea,numerical__WoodDeckSF,numerical__OpenPorchSF,numerical__EnclosedPorch,numerical__3SsnPorch,numerical__ScreenPorch,numerical__PoolArea,numerical__MiscVal,numerical__MoSold,numerical__YrSold,categorical__MSZoning_C (all),categorical__MSZoning_FV,categorical__MSZoning_RH,categorical__MSZoning_RL,categorical__MSZoning_RM,categorical__Street_Grvl,categorical__Street_Pave,categorical__LotShape_IR1,categorical__LotShape_IR2,categorical__LotShape_IR3,categorical__LotShape_Reg,categorical__LandContour_Bnk,categorical__LandContour_HLS,categorical__LandContour_Low,categorical__LandContour_Lvl,categorical__Utilities_AllPub,categorical__Utilities_NoSeWa,categorical__LotConfig_Corner,categorical__LotConfig_CulDSac,categorical__LotConfig_FR2,categorical__LotConfig_FR3,categorical__LotConfig_Inside,categorical__LandSlope_Gtl,categorical__LandSlope_Mod,categorical__LandSlope_Sev,categorical__Neighborhood_Blmngtn,categorical__Neighborhood_Blueste,categorical__Neighborhood_BrDale,categorical__Neighborhood_BrkSide,categorical__Neighborhood_ClearCr,categorical__Neighborhood_CollgCr,categorical__Neighborhood_Crawfor,categorical__Neighborhood_Edwards,categorical__Neighborhood_Gilbert,categorical__Neighborhood_IDOTRR,categorical__Neighborhood_MeadowV,categorical__Neighborhood_Mitchel,categorical__Neighborhood_NAmes,categorical__Neighborhood_NPkVill,categorical__Neighborhood_NWAmes,categorical__Neighborhood_NoRidge,categorical__Neighborhood_NridgHt,categorical__Neighborhood_OldTown,categorical__Neighborhood_SWISU,categorical__Neighborhood_Sawyer,categorical__Neighborhood_SawyerW,categorical__Neighborhood_Somerst,categorical__Neighborhood_StoneBr,categorical__Neighborhood_Timber,categorical__Neighborhood_Veenker,categorical__Condition1_Artery,categorical__Condition1_Feedr,categorical__Condition1_Norm,categorical__Condition1_PosA,categorical__Condition1_PosN,categorical__Condition1_RRAe,categorical__Condition1_RRAn,categorical__Condition1_RRNe,categorical__Condition1_RRNn,categorical__Condition2_Artery,categorical__Condition2_Feedr,categorical__Condition2_Norm,categorical__Condition2_PosA,categorical__Condition2_PosN,categorical__Condition2_RRAe,categorical__Condition2_RRAn,categorical__Condition2_RRNn,categorical__BldgType_1Fam,categorical__BldgType_2fmCon,categorical__BldgType_Duplex,categorical__BldgType_Twnhs,categorical__BldgType_TwnhsE,categorical__HouseStyle_1.5Fin,categorical__HouseStyle_1.5Unf,categorical__HouseStyle_1Story,categorical__HouseStyle_2.5Fin,categorical__HouseStyle_2.5Unf,categorical__HouseStyle_2Story,categorical__HouseStyle_SFoyer,categorical__HouseStyle_SLvl,categorical__RoofStyle_Flat,categorical__RoofStyle_Gable,categorical__RoofStyle_Gambrel,categorical__RoofStyle_Hip,categorical__RoofStyle_Mansard,categorical__RoofStyle_Shed,categorical__RoofMatl_ClyTile,categorical__RoofMatl_CompShg,categorical__RoofMatl_Metal,categorical__RoofMatl_Roll,categorical__RoofMatl_Tar&Grv,categorical__RoofMatl_WdShake,categorical__RoofMatl_WdShngl,categorical__Exterior1st_AsbShng,categorical__Exterior1st_AsphShn,categorical__Exterior1st_BrkComm,categorical__Exterior1st_BrkFace,categorical__Exterior1st_CBlock,categorical__Exterior1st_CemntBd,categorical__Exterior1st_HdBoard,categorical__Exterior1st_ImStucc,categorical__Exterior1st_MetalSd,categorical__Exterior1st_Plywood,categorical__Exterior1st_Stone,categorical__Exterior1st_Stucco,categorical__Exterior1st_VinylSd,categorical__Exterior1st_Wd Sdng,categorical__Exterior1st_WdShing,categorical__Exterior2nd_AsbShng,categorical__Exterior2nd_AsphShn,categorical__Exterior2nd_Brk Cmn,categorical__Exterior2nd_BrkFace,categorical__Exterior2nd_CBlock,categorical__Exterior2nd_CmentBd,categorical__Exterior2nd_HdBoard,categorical__Exterior2nd_ImStucc,categorical__Exterior2nd_MetalSd,categorical__Exterior2nd_Other,categorical__Exterior2nd_Plywood,categorical__Exterior2nd_Stone,categorical__Exterior2nd_Stucco,categorical__Exterior2nd_VinylSd,categorical__Exterior2nd_Wd Sdng,categorical__Exterior2nd_Wd Shng,categorical__ExterQual_Ex,categorical__ExterQual_Fa,categorical__ExterQual_Gd,categorical__ExterQual_TA,categorical__ExterCond_Ex,categorical__ExterCond_Fa,categorical__ExterCond_Gd,categorical__ExterCond_Po,categorical__ExterCond_TA,categorical__Foundation_BrkTil,categorical__Foundation_CBlock,categorical__Foundation_PConc,categorical__Foundation_Slab,categorical__Foundation_Stone,categorical__Foundation_Wood,categorical__BsmtQual_Ex,categorical__BsmtQual_Fa,categorical__BsmtQual_Gd,categorical__BsmtQual_TA,categorical__BsmtCond_Fa,categorical__BsmtCond_Gd,categorical__BsmtCond_Po,categorical__BsmtCond_TA,categorical__BsmtExposure_Av,categorical__BsmtExposure_Gd,categorical__BsmtExposure_Mn,categorical__BsmtExposure_No,categorical__BsmtFinType1_ALQ,categorical__BsmtFinType1_BLQ,categorical__BsmtFinType1_GLQ,categorical__BsmtFinType1_LwQ,categorical__BsmtFinType1_Rec,categorical__BsmtFinType1_Unf,categorical__BsmtFinType2_ALQ,categorical__BsmtFinType2_BLQ,categorical__BsmtFinType2_GLQ,categorical__BsmtFinType2_LwQ,categorical__BsmtFinType2_Rec,categorical__BsmtFinType2_Unf,categorical__Heating_Floor,categorical__Heating_GasA,categorical__Heating_GasW,categorical__Heating_Grav,categorical__Heating_OthW,categorical__Heating_Wall,categorical__HeatingQC_Ex,categorical__HeatingQC_Fa,categorical__HeatingQC_Gd,categorical__HeatingQC_Po,categorical__HeatingQC_TA,categorical__CentralAir_N,categorical__CentralAir_Y,categorical__Electrical_FuseA,categorical__Electrical_FuseF,categorical__Electrical_FuseP,categorical__Electrical_SBrkr,categorical__KitchenQual_Ex,categorical__KitchenQual_Fa,categorical__KitchenQual_Gd,categorical__KitchenQual_TA,categorical__Functional_Maj1,categorical__Functional_Maj2,categorical__Functional_Min1,categorical__Functional_Min2,categorical__Functional_Mod,categorical__Functional_Sev,categorical__Functional_Typ,categorical__FireplaceQu_Ex,categorical__FireplaceQu_Fa,categorical__FireplaceQu_Gd,categorical__FireplaceQu_Po,categorical__FireplaceQu_TA,categorical__GarageType_2Types,categorical__GarageType_Attchd,categorical__GarageType_Basment,categorical__GarageType_BuiltIn,categorical__GarageType_CarPort,categorical__GarageType_Detchd,categorical__GarageFinish_Fin,categorical__GarageFinish_RFn,categorical__GarageFinish_Unf,categorical__GarageQual_Ex,categorical__GarageQual_Fa,categorical__GarageQual_Gd,categorical__GarageQual_Po,categorical__GarageQual_TA,categorical__GarageCond_Ex,categorical__GarageCond_Fa,categorical__GarageCond_Gd,categorical__GarageCond_Po,categorical__GarageCond_TA,categorical__PavedDrive_N,categorical__PavedDrive_P,categorical__PavedDrive_Y,categorical__SaleType_COD,categorical__SaleType_CWD,categorical__SaleType_Con,categorical__SaleType_ConLD,categorical__SaleType_ConLI,categorical__SaleType_ConLw,categorical__SaleType_New,categorical__SaleType_Oth,categorical__SaleType_WD,categorical__SaleCondition_Abnorml,categorical__SaleCondition_AdjLand,categorical__SaleCondition_Alloca,categorical__SaleCondition_Family,categorical__SaleCondition_Normal,categorical__SaleCondition_Partial
0,-1.119284,-0.866764,-0.015314,-0.212896,-0.820445,0.372217,-0.455469,-1.346063,-0.601531,1.037269,-0.285504,-0.400282,0.572612,0.374235,-0.801923,-0.118999,-0.407093,1.105320,-0.24287,-1.055566,-0.764098,0.136218,-0.212757,-0.964566,-0.958592,-9.014248e-01,-1.056544,-0.863837,1.188402,-0.714352,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-0.133417,1.650065,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.790464,0.074110,-0.505211,-0.265245,-0.088934,1.268609,0.718609,0.439214,-0.601531,-0.971996,-0.285504,0.511920,-0.596547,-0.958202,0.955088,-0.118999,0.083170,-0.818694,-0.24287,0.773664,1.236947,0.136218,-0.212757,0.270755,0.592150,5.966403e-01,0.295092,-0.456264,-0.740157,-0.138015,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-0.508010,0.893677,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,-0.216152,-0.631546,-0.148922,-0.177841,-0.820445,1.268609,-1.988293,-1.683818,-0.601531,-0.971996,-0.285504,0.505196,-0.603357,-0.965964,-0.801923,-0.118999,-1.395250,-0.818694,-0.24287,-1.055566,-0.764098,-1.106774,-0.212757,-1.582227,-0.958592,-1.892337e-14,-2.408179,-2.257169,1.790113,-0.714352,2.290826,-0.121008,-0.275838,-0.070993,-0.09274,-0.508010,0.137290,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.162505,-0.161109,-0.460675,-0.324474,-0.820445,1.268609,-1.107734,-1.683818,0.859229,0.267995,-0.285504,-0.915776,-0.750921,-0.487321,0.989227,-0.118999,0.458975,1.105320,-0.24287,-1.055566,1.236947,0.136218,-0.212757,0.270755,2.142892,-1.650457e+00,-1.056544,-1.119755,-0.740157,-0.714352,3.902257,-0.121008,-0.275838,-0.070993,-0.09274,-0.133417,-0.619098,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.822944,-0.161109,-0.906036,-0.529035,-0.820445,0.372217,-1.531707,-1.683818,-0.601531,-0.496920,-0.285504,0.532091,-0.081209,-0.370895,0.711564,-0.118999,0.312087,-0.818694,-0.24287,0.773664,-0.764098,0.136218,-0.212757,-0.346905,0.592150,-2.274651e+00,-1.056544,-0.797488,-0.740157,-0.714352,3.547742,-0.121008,-0.275838,-0.070993,-0.09274,-0.508010,1.650065,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [31]:
X_train_transformed.shape

(1168, 270)

In [32]:
X_train_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1168 entries, 0 to 1167
Columns: 270 entries, numerical__Id to categorical__SaleCondition_Partial
dtypes: float64(270)
memory usage: 2.4 MB

In [33]:
base_models = [
    ('rf', RandomForestRegressor(n_estimators=100, random_state=42)),
    ('gbr', GradientBoostingRegressor(n_estimators=100, random_state=42)),
    ('svr', SVR(kernel='rbf', C=10))
]

In [34]:
meta_model = Ridge(alpha=1.0)

In [35]:
stacking_regressor = StackingRegressor(estimators=base_models, final_estimator=meta_model)

In [36]:
stacking_regressor.fit(X_train_transformed, y_train)
y_pred = stacking_regressor.predict(X_val_transformed)

mse = mean_squared_error(y_val, y_pred)

print("Model MSE:", mse)

mae = mean_absolute_error(y_val, y_pred)

print("Model MAE:", mae)

rmse = np.sqrt(mse)

print ("Model RMSE:", rmse)


r2 = r2_score(y_val, y_pred)

print ("Model R2:", r2)

Model MSE: 704797479.1032296
Model MAE: 16558.615233618893
Model RMSE: 26548.02213166227
Model R2: 0.9081137542178022

In [37]:
baseline_pred = y_train.mean()
baseline_mse = np.mean((y_val - baseline_pred) ** 2)
print("Baseline MSE:", baseline_mse)

Baseline MSE: 7677095207.783831

In [38]:
X_test_transformed.head()

,numerical__Id,numerical__MSSubClass,numerical__LotFrontage,numerical__LotArea,numerical__OverallQual,numerical__OverallCond,numerical__YearBuilt,numerical__YearRemodAdd,numerical__MasVnrArea,numerical__BsmtFinSF1,numerical__BsmtFinSF2,numerical__BsmtUnfSF,numerical__TotalBsmtSF,numerical__1stFlrSF,numerical__2ndFlrSF,numerical__LowQualFinSF,numerical__GrLivArea,numerical__BsmtFullBath,numerical__BsmtHalfBath,numerical__FullBath,numerical__HalfBath,numerical__BedroomAbvGr,numerical__KitchenAbvGr,numerical__TotRmsAbvGrd,numerical__Fireplaces,numerical__GarageYrBlt,numerical__GarageCars,numerical__GarageArea,numerical__WoodDeckSF,numerical__OpenPorchSF,numerical__EnclosedPorch,numerical__3SsnPorch,numerical__ScreenPorch,numerical__PoolArea,numerical__MiscVal,numerical__MoSold,numerical__YrSold,categorical__MSZoning_C (all),categorical__MSZoning_FV,categorical__MSZoning_RH,categorical__MSZoning_RL,categorical__MSZoning_RM,categorical__Street_Grvl,categorical__Street_Pave,categorical__LotShape_IR1,categorical__LotShape_IR2,categorical__LotShape_IR3,categorical__LotShape_Reg,categorical__LandContour_Bnk,categorical__LandContour_HLS,categorical__LandContour_Low,categorical__LandContour_Lvl,categorical__Utilities_AllPub,categorical__Utilities_NoSeWa,categorical__LotConfig_Corner,categorical__LotConfig_CulDSac,categorical__LotConfig_FR2,categorical__LotConfig_FR3,categorical__LotConfig_Inside,categorical__LandSlope_Gtl,categorical__LandSlope_Mod,categorical__LandSlope_Sev,categorical__Neighborhood_Blmngtn,categorical__Neighborhood_Blueste,categorical__Neighborhood_BrDale,categorical__Neighborhood_BrkSide,categorical__Neighborhood_ClearCr,categorical__Neighborhood_CollgCr,categorical__Neighborhood_Crawfor,categorical__Neighborhood_Edwards,categorical__Neighborhood_Gilbert,categorical__Neighborhood_IDOTRR,categorical__Neighborhood_MeadowV,categorical__Neighborhood_Mitchel,categorical__Neighborhood_NAmes,categorical__Neighborhood_NPkVill,categorical__Neighborhood_NWAmes,categorical__Neighborhood_NoRidge,categorical__Neighborhood_NridgHt,categorical__Neighborhood_OldTown,categorical__Neighborhood_SWISU,categorical__Neighborhood_Sawyer,categorical__Neighborhood_SawyerW,categorical__Neighborhood_Somerst,categorical__Neighborhood_StoneBr,categorical__Neighborhood_Timber,categorical__Neighborhood_Veenker,categorical__Condition1_Artery,categorical__Condition1_Feedr,categorical__Condition1_Norm,categorical__Condition1_PosA,categorical__Condition1_PosN,categorical__Condition1_RRAe,categorical__Condition1_RRAn,categorical__Condition1_RRNe,categorical__Condition1_RRNn,categorical__Condition2_Artery,categorical__Condition2_Feedr,categorical__Condition2_Norm,categorical__Condition2_PosA,categorical__Condition2_PosN,categorical__Condition2_RRAe,categorical__Condition2_RRAn,categorical__Condition2_RRNn,categorical__BldgType_1Fam,categorical__BldgType_2fmCon,categorical__BldgType_Duplex,categorical__BldgType_Twnhs,categorical__BldgType_TwnhsE,categorical__HouseStyle_1.5Fin,categorical__HouseStyle_1.5Unf,categorical__HouseStyle_1Story,categorical__HouseStyle_2.5Fin,categorical__HouseStyle_2.5Unf,categorical__HouseStyle_2Story,categorical__HouseStyle_SFoyer,categorical__HouseStyle_SLvl,categorical__RoofStyle_Flat,categorical__RoofStyle_Gable,categorical__RoofStyle_Gambrel,categorical__RoofStyle_Hip,categorical__RoofStyle_Mansard,categorical__RoofStyle_Shed,categorical__RoofMatl_ClyTile,categorical__RoofMatl_CompShg,categorical__RoofMatl_Metal,categorical__RoofMatl_Roll,categorical__RoofMatl_Tar&Grv,categorical__RoofMatl_WdShake,categorical__RoofMatl_WdShngl,categorical__Exterior1st_AsbShng,categorical__Exterior1st_AsphShn,categorical__Exterior1st_BrkComm,categorical__Exterior1st_BrkFace,categorical__Exterior1st_CBlock,categorical__Exterior1st_CemntBd,categorical__Exterior1st_HdBoard,categorical__Exterior1st_ImStucc,categorical__Exterior1st_MetalSd,categorical__Exterior1st_Plywood,categorical__Exterior1st_Stone,categorical__Exterior1st_Stucco,categorical__Exterior1st_VinylSd,categorical__Exterior1st_Wd Sdng,categorical__Exterior1st_WdShing,categorical__Exterior2nd_AsbShng,categorical__Exterior2nd_AsphShn,categorical__Exterior2nd_Brk Cmn,categorical__Exterior2nd_BrkFace,categorical__Exterior2nd_CBlock,categorical__Exterior2nd_CmentBd,categorical__Exterior2nd_HdBoard,categorical__Exterior2nd_ImStucc,categorical__Exterior2nd_MetalSd,categorical__Exterior2nd_Other,categorical__Exterior2nd_Plywood,categorical__Exterior2nd_Stone,categorical__Exterior2nd_Stucco,categorical__Exterior2nd_VinylSd,categorical__Exterior2nd_Wd Sdng,categorical__Exterior2nd_Wd Shng,categorical__ExterQual_Ex,categorical__ExterQual_Fa,categorical__ExterQual_Gd,categorical__ExterQual_TA,categorical__ExterCond_Ex,categorical__ExterCond_Fa,categorical__ExterCond_Gd,categorical__ExterCond_Po,categorical__ExterCond_TA,categorical__Foundation_BrkTil,categorical__Foundation_CBlock,categorical__Foundation_PConc,categorical__Foundation_Slab,categorical__Foundation_Stone,categorical__Foundation_Wood,categorical__BsmtQual_Ex,categorical__BsmtQual_Fa,categorical__BsmtQual_Gd,categorical__BsmtQual_TA,categorical__BsmtCond_Fa,categorical__BsmtCond_Gd,categorical__BsmtCond_Po,categorical__BsmtCond_TA,categorical__BsmtExposure_Av,categorical__BsmtExposure_Gd,categorical__BsmtExposure_Mn,categorical__BsmtExposure_No,categorical__BsmtFinType1_ALQ,categorical__BsmtFinType1_BLQ,categorical__BsmtFinType1_GLQ,categorical__BsmtFinType1_LwQ,categorical__BsmtFinType1_Rec,categorical__BsmtFinType1_Unf,categorical__BsmtFinType2_ALQ,categorical__BsmtFinType2_BLQ,categorical__BsmtFinType2_GLQ,categorical__BsmtFinType2_LwQ,categorical__BsmtFinType2_Rec,categorical__BsmtFinType2_Unf,categorical__Heating_Floor,categorical__Heating_GasA,categorical__Heating_GasW,categorical__Heating_Grav,categorical__Heating_OthW,categorical__Heating_Wall,categorical__HeatingQC_Ex,categorical__HeatingQC_Fa,categorical__HeatingQC_Gd,categorical__HeatingQC_Po,categorical__HeatingQC_TA,categorical__CentralAir_N,categorical__CentralAir_Y,categorical__Electrical_FuseA,categorical__Electrical_FuseF,categorical__Electrical_FuseP,categorical__Electrical_SBrkr,categorical__KitchenQual_Ex,categorical__KitchenQual_Fa,categorical__KitchenQual_Gd,categorical__KitchenQual_TA,categorical__Functional_Maj1,categorical__Functional_Maj2,categorical__Functional_Min1,categorical__Functional_Min2,categorical__Functional_Mod,categorical__Functional_Sev,categorical__Functional_Typ,categorical__FireplaceQu_Ex,categorical__FireplaceQu_Fa,categorical__FireplaceQu_Gd,categorical__FireplaceQu_Po,categorical__FireplaceQu_TA,categorical__GarageType_2Types,categorical__GarageType_Attchd,categorical__GarageType_Basment,categorical__GarageType_BuiltIn,categorical__GarageType_CarPort,categorical__GarageType_Detchd,categorical__GarageFinish_Fin,categorical__GarageFinish_RFn,categorical__GarageFinish_Unf,categorical__GarageQual_Ex,categorical__GarageQual_Fa,categorical__GarageQual_Gd,categorical__GarageQual_Po,categorical__GarageQual_TA,categorical__GarageCond_Ex,categorical__GarageCond_Fa,categorical__GarageCond_Gd,categorical__GarageCond_Po,categorical__GarageCond_TA,categorical__PavedDrive_N,categorical__PavedDrive_P,categorical__PavedDrive_Y,categorical__SaleType_COD,categorical__SaleType_CWD,categorical__SaleType_Con,categorical__SaleType_ConLD,categorical__SaleType_ConLI,categorical__SaleType_ConLw,categorical__SaleType_New,categorical__SaleType_Oth,categorical__SaleType_WD,categorical__SaleCondition_Abnorml,categorical__SaleCondition_AdjLand,categorical__SaleCondition_Alloca,categorical__SaleCondition_Family,categorical__SaleCondition_Normal,categorical__SaleCondition_Partial
0,1.717115,-0.866764,0.430047,0.086693,-0.820445,0.372217,-0.325016,-1.153060,-0.601531,0.047891,0.625025,-0.673718,-0.408119,-0.707238,-0.801923,-0.118999,-1.204486,-0.818694,-0.24287,-1.055566,-0.764098,-1.106774,-0.212757,-0.964566,-0.958592,-0.734973,-1.056544,1.202465,0.339836,-0.714352,-0.351921,-0.121008,1.872497,-0.070993,-0.092740,-0.133417,1.650065,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.719467,-0.866764,0.474583,0.332630,-0.088934,0.372217,-0.422856,-1.297812,0.024509,1.039448,-0.285504,-0.368904,0.606665,0.413044,-0.801923,-0.118999,-0.378479,-0.818694,-0.24287,-1.055566,1.236947,0.136218,-0.212757,-0.346905,-0.958592,-0.859812,-1.056544,-0.778531,2.291539,-0.195649,-0.351921,-0.121008,-0.275838,-0.070993,22.519298,-0.133417,1.650065,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.721819,0.074110,0.162831,0.291997,-0.820445,-0.524174,0.849062,0.632217,-0.601531,0.751787,-0.285504,-0.971808,-0.303689,-0.624446,0.793497,-0.118999,0.193813,-0.818694,-0.24287,0.773664,1.236947,0.136218,-0.212757,-0.346905,0.592150,0.763092,0.295092,0.027137,0.895261,-0.224465,-0.351921,-0.121008,-0.275838,-0.070993,-0.092740,-1.257196,1.650065,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.724171,0.074110,0.340975,-0.066170,-0.088934,0.372217,0.881675,0.632217,-0.485598,0.339910,-0.285504,-0.552689,-0.308230,-0.629621,0.741151,-0.118999,0.146122,-0.818694,-0.24287,0.773664,1.236947,0.136218,-0.212757,0.270755,0.592150,0.804705,0.295092,-0.029734,2.036969,-0.195649,-0.351921,-0.121008,-0.275838,-0.070993,-0.092740,-0.133417,1.650065,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.726523,1.485421,-1.217789,-0.528570,1.374088,-0.524174,0.685996,0.342712,-0.601531,-0.398854,-0.285504,1.000519,0.495425,0.286268,-0.801923,-0.118999,-0.471953,-0.818694,-0.24287,0.773664,-0.764098,-1.106774,-0.212757,-0.964566,-0.958592,0.555027,0.295092,0.140878,-0.740157,0.467139,-0.351921,-0.121008,2.302164,-0.070993,-0.092740,-2.006382,1.650065,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [39]:
X_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,6,1998,1998,Gable,CompShg,VinylSd,VinylSd,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926,678,0,1604,0.0,0.0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360,36,0,0,0,0,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1992,1992,Gable,CompShg,HdBoard,HdBoard,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280,0,0,1280,0.0,0.0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0,82,0,0,144,0,0,1,2010,WD,Normal

In [40]:

y_pred = stacking_regressor.predict(X_test_transformed)


ids = X_test['Id']


submission_df = pd.DataFrame({
    'ID': ids,              
    'SalePrice': y_pred 
})

submission_df = submission_df.set_index('ID')


submission_df.to_csv('submission.csv')